### ISSUE TITLE
如何安装依赖包

### ISSUE THREAD

**Issue by GQ-Jesse** [liepeng328/angular-base#3]
你好！
      最近刚好在学习angular4，因此将你在github上面的项目克隆到了我的svn。但是克隆到本地后发现是没有依赖包的node_modules，启动不起来，请问我要怎么安装依赖包？

**Comment by liepeng328** [comment]
进入文件夹，管理员权限执行 npm install

**Comment by xiaoCong2014** [comment]
如果 npm install 后仍然无法启动项目 , 就手动删除刚刚下载好的 node_modules 文件夹 , 用 cnpm 重装一下依赖包 , 具体操作百度吧 .
