### ISSUE TITLE
提示全局angular-cli版本比依赖包要求的cli版本高，怎么办？

### ISSUE THREAD

**Issue by GQ-Jesse** [liepeng328/angular-base#4]
![image](https://user-images.githubusercontent.com/27001132/31881012-c80d28b0-b814-11e7-9796-9417bcee11bf.png)

**Comment by liepeng328** [comment]
运行这个就把这个提示去掉了
![image](https://user-images.githubusercontent.com/19989280/31881145-3c68467c-b815-11e7-945c-d240db118fd1.png)

正常开发，版本低一些好，新版的不稳定。

关键是你下边有个报错。
![image](https://user-images.githubusercontent.com/19989280/31881180-5d6c91ac-b815-11e7-9fa0-e4b8f07f0bc4.png)
重新npm install一次试试，没装完整吧。

你可以试试图形界面化开发，不用命令行。我用的idea开发工具
![image](https://user-images.githubusercontent.com/19989280/31881223-8109605e-b815-11e7-8849-1d57c7316a08.png)

**Comment by xiaoCong2014** [comment]
最懒的方法 , 直接无视这个提示 ( 提示全局 angular-cli 版本比较高 )  , 因为它不影响后续的开发 .

**Comment by liepeng328** [comment]
运行这个就把这个提示去掉了
![image](https://user-images.githubusercontent.com/19989280/31920445-9577be6a-b89b-11e7-8372-03bd25137aa6.png)
提示很清楚了

**Comment by liepeng328** [comment]
因为我开发这个项目的时候是一个月以前，开发的过程中angular-cli肯定是不断升级的。你可以修改配置，改到最新版，但是不建议改，package.json中有配置版本号的。最新版不稳定，不建议改
