### ISSUE TITLE
文档格式好乱，建议增加如下内容。

### ISSUE THREAD

**Issue by yooRabbit** [liepeng328/angular-base#5]
#Feature
搭建过程、创建组件和指令等的过程。
打包的aot也应该说一下，毕竟官方就靠这个吹。
文档内容得整理下，开箱即用也得好好给个说明吧，非要加qq群讨论吗。。。
另外在别人issues里面打广告 确实很不好

**Comment by liepeng328** [comment]
搭建过程、创建组件和指令等的过程。这个都是软件做，idea中鼠标点击就行了
aot angular官方说的很详细，我再说就多余了
qq群是大家交流的
issues我不知道是做什么的，后来知道了，就全删了
